cmake_minimum_required(VERSION 3.22.1)
project(companion_jni C CXX)

foreach(o BUILD_SHARED_LIBS GGML_LTO GGML_OPENMP GGML_NATIVE GGML_LLAMAFILE LLAMA_CURL LLAMA_OPENSSL LLAMA_BUILD_COMMON LLAMA_BUILD_TESTS LLAMA_BUILD_TOOLS LLAMA_BUILD_EXAMPLES LLAMA_BUILD_SERVER LLAMA_BUILD_APP)
    set(${o} OFF CACHE BOOL "" FORCE)
endforeach()
foreach(o GGML_CPU_KLEIDIAI FETCHCONTENT_FULLY_DISCONNECTED)
    set(${o} ON CACHE BOOL "" FORCE)
endforeach()
set(GGML_CPU_ARM_ARCH armv8.6-a+dotprod+i8mm CACHE STRING "" FORCE)
set(FETCHCONTENT_SOURCE_DIR_KLEIDIAI ${KLEIDIAI_DIR} CACHE PATH "" FORCE)
foreach(c DEBUG RELEASE RELWITHDEBINFO)
    set(CMAKE_C_FLAGS_${c} "-O3 -DNDEBUG")
    set(CMAKE_CXX_FLAGS_${c} "-O3 -DNDEBUG")
endforeach()
string(APPEND CMAKE_C_FLAGS " -flto=thin")
string(APPEND CMAKE_CXX_FLAGS " -flto=thin")
string(APPEND CMAKE_SHARED_LINKER_FLAGS " -flto=thin")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

add_subdirectory(${LLAMA_DIR} llama EXCLUDE_FROM_ALL)

add_library(llm_jni SHARED nux_jni.cpp chat_jni.cpp)
target_compile_options(llm_jni PRIVATE -Wall -Werror -fvisibility=hidden -O3)
target_link_libraries(llm_jni PRIVATE llama)
target_link_options(llm_jni PRIVATE -Wl,--exclude-libs,ALL -Wl,-z,max-page-size=16384 -Wl,--gc-sections)
